use cdac1;
select concat('this ','is ','a ','class ','for ','employee');
select first_name,last_name,concat(first_name,' ',last_name) name from employees order by name desc;
select *,concat(first_name,'earns',salary) name from employees;
select last_name,manager_id,concat(last_name,' is under ',manager_id) from employees;
select substr('helloworld',-6,5);
select email,substr(email,1,3) from employees;
select substring_index('www.abc.com','.',-2);
select email,substring_index(email,'@',-1),substring_index(email,'@',1) from employees;
select substring_index('https://www.test.com','/',2);
select instr('helloworld','l');
select last_name,instr(last_name,'a') from employees;
select lpad('helloworld',15,'#'),rpad('helloworld',15,'#');
select phone_number,rpad(phone_number,20,'#') from employees;
select concat(rpad(substr('hello',1,2),6,'*'),substr('hello',-3,3));
select length('helloworld');
select first_name,length(first_name) from employees;
select trim('h' from 'helloworld'),trim('d' from 'helloworld');
select concat(trim('o' from substr('helloworld',1,5)),substr('helloworld',-5,5));
select replace('helloworld','hello','abcd');
select repeat('hello',2);
select reverse('hello');
select abs(-90),abs(90);
select ceil(89.9),floor(89.9),ceil(89.1),floor(89.1);
select greatest(12,34,56,78),least(12,34,56,78);
select greatest(salary,department_id,manager_id),least(salary,department_id,manager_id) from employees;
select mod(324,3);
select salary,mod(salary,3) from employees;
select pow(3,23);
select round(45.67,1),truncate(45.63,1),round(44.67,-1),truncate(45.67,-1),round(45.67,0),truncate(45.67,0),round(45,1);
select round(45.65,1);
